"""make snippet titles unique

Revision ID: 011db2489978
Revises: e1a482e49f90
Create Date: 2026-04-30 19:11:11.467001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011db2489978'
down_revision: Union[str, Sequence[str], None] = 'e1a482e49f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippets_title'), table_name='snippets')
    op.create_index(op.f('ix_snippets_title'), 'snippets', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippets_title'), table_name='snippets')
    op.create_index(op.f('ix_snippets_title'), 'snippets', ['title'], unique=False)
    # ### end Alembic commands ###
