"""first alembic migration

Revision ID: b10bba9bc309
Revises: 
Create Date: 2026-04-24 18:06:50.414752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b10bba9bc309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snippets', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snippets', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snippets', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snippets', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snippets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('snippets', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('snippets', 'last_updated_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_snippets_owner_id'), 'snippets', ['owner_id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_snippets_owner_id'), table_name='snippets')
    op.alter_column('snippets', 'last_updated_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('snippets', 'creation_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('snippets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('snippets', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snippets', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snippets', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snippets', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
